version: '3'
services:
 mongodb:
  image: mongo
  ports:
   - 27017:27017
  environment:
   - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
   - ME_CONFIG_MONGODB_ADMINPASSWORD=password

 mongo-express:
  image: mongo-express
  ports:
   - 8081:8081
  environment:
   - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
   - ME_CONFIG_MONGODB_ADMINPASSWORD=password
   - ME_CONFIG_MONGODB_SERVER=mongodb
   - ME_CONFIG_MONGODB_PORT=27017
  depends_on:
   - mongodb


